### PR TITLE
chore: Adds dependabot support for automated dependency management

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

This PR adds dependabot support for automating dependency management, just like it is done in other SD-Core repos like the [AMF](https://github.com/omec-project/amf) and [NRF](https://github.com/omec-project/nrf). Dependabot will automatically create pull requests, all we have to do is review and merge those.

## Rationale

Managing dependencies is critical for stability and security purposes and it's very difficult to stay up to date on a best effort basis.

### CODE REVIEW

**Comment by gab-arrobo** [comment]
test this please

**Comment by gruyaume** [comment]
@gab-arrobo @thakurajayL Can this PR receive some reviews?

**Comment by gab-arrobo** [comment]
> @gab-arrobo @thakurajayL Can this PR receive some reviews?

Hi @gruyaume, I have not approved and merged this PR as of yet because I need some help from @dafATonf making some setting updates in this repo. This PR is pretty straightforward to review/approve and as soon as @dafATonf helps me with the request I sent to him last week about this repo, I can merge it.

**Review by gab-arrobo — APPROVED** [review]
+1

**Pull request merged**
